# Generated by Django 4.1.7 on 2023-03-30 03:33

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
            ],
        ),
    ]
