# Generated by Django 4.1.7 on 2023-03-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
