# Generated by Django 4.1.7 on 2023-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pic', models.FileField(default='bg_def.jpg', upload_to='files')),
            ],
        ),
    ]
